version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: medguard_db
      POSTGRES_USER: medguard_user
      POSTGRES_PASSWORD: medguard_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medguard_user -d medguard_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: