# Generated by Django 4.2.24 on 2025-09-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_donne', models.CharField(max_length=50)),
                ('valeur', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='patients.patient')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
